using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using Unity.VisualScripting;
using UnityEditor;
using UnityEngine;

namespace UsefulUtilities
{
    /// <summary>
    /// Automatically generates HLSL structs/enums/constants from C# structs/enums/readonly structs marked with the [SharedStruct] attribute.
    /// Enums are automatically converted to define symbols (e.g '#define MyEnumName_FieldName FieldValue'). To generate constants, use a
    /// readonly struct marked with the [SharedStruct] attribute, using const or static readonly variables
    /// </summary>
    public class SharedStructs : AssetPostprocessor
    {
        private const string OUTPUT_DIRECTORY = "Auto Generated HLSL Structs";
        private const string OUTPUT_FILE_SUFFIX = "_AutoGenerated";
        private const string OUTPUT_FILE_EXTENSION = ".hlsl";
        //hlsl to c# type links
        private static readonly LinkedType[] linkedTypes = new LinkedType[]
        {
            new LinkedType("int", typeof(int), false),
            new LinkedType("int2", typeof(Vector2Int), true),
            new LinkedType("int3", typeof(Vector3Int), true),
            new LinkedType("uint", typeof(uint), false),
            new LinkedType("float", typeof(float), false),
            new LinkedType("float2", typeof(Vector2), true),
            new LinkedType("float3", typeof(Vector3), true),
            new LinkedType("float4", typeof(Vector4), true),
            new LinkedType("float4x4", typeof(Matrix4x4), true)
        };

        private static readonly Type[] unsupportedBuiltInTypes = new Type[]
        {
            typeof(bool),
            typeof(byte),
            typeof(sbyte),
            typeof(char),
            typeof(decimal),
            typeof(double),
            typeof(nint),
            typeof(nuint),
            typeof(long),
            typeof(ulong),
            typeof(short),
            typeof(ushort),
            typeof(object),
            typeof(string),
            typeof(void)
        };


        private struct LinkedType
        {
            public string hlslType;
            public Type cSharpType;
            public bool displayTypeNameInValueAssignment;

            public LinkedType(string hlslType, Type cSharpType, bool displayTypeNameInValueAssignment)
            {
                this.hlslType = hlslType;
                this.cSharpType = cSharpType;
                this.displayTypeNameInValueAssignment = displayTypeNameInValueAssignment;
            }
        }

        private struct Struct
        {
            public string name;
            public Type type;
            public List<Variable> variables;
            public List<Struct> references;
            public string fileName;

            public Struct(string name)
            {
                this.name = name;
                type = null;
                variables = null;
                references = null;
                fileName = null;
            }

            public Struct(string name, Type type)
            {
                this.name = name;
                this.type = type;
                variables = new List<Variable>();
                references = new List<Struct>();
                fileName = null;
            }

            public Struct(Type type, string fileName)
            {
                name = null;
                this.type = type;
                variables = new List<Variable>();
                references = new List<Struct>();
                this.fileName = fileName;
            }

            public Struct(Type type)
            {
                name = null;
                this.type = type;
                variables = new List<Variable>();
                references = new List<Struct>();
                fileName = null;
            }

            public Struct(string name, List<Variable> variables)
            {
                this.name = name;
                this.type = null;
                this.variables = variables;
                references = new List<Struct>();
                fileName = null;
            }

            public Struct(string name, Type type, string fileName)
            {
                this.name = name;
                this.type = type;
                variables = new List<Variable>();
                references = new List<Struct>();
                this.fileName = fileName;
            }
        }

        private struct Variable
        {
            public string name;
            public string type;
            public List<string> values;
            public int arrayLength;

            public Variable(string name, string type, List<string> values, int arrayLength)
            {
                this.name = name;
                this.type = type;
                this.values = values;
                this.arrayLength = arrayLength;
            }

            public Variable(string name, string type, int arrayLength)
            {
                this.name = name;
                this.type = type;
                values = new List<string>();
                this.arrayLength = arrayLength;
            }

            public Variable(string name, List<string> values)
            {
                this.name = name;
                type = null;
                this.values = values;
                arrayLength = 0;
            }

            public Variable(string name, string type, string value)
            {
                this.name = name;
                this.type = type;
                values = new List<string>() { value };
                arrayLength = 0;
            }
        }


        public static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
        {
            bool fileGenerated = false;

            foreach (string assetPath in importedAssets)
            {
                //get all .cs files except this one
                if (assetPath.EndsWith(".cs") && Path.GetFileNameWithoutExtension(assetPath) != typeof(SharedStructs).Name)
                {
                    fileGenerated = ProcessFile(assetPath);
                }
            }

            //refresh the assets if a file was generated to show the changes
            if (fileGenerated)
            {
                AssetDatabase.Refresh();
            }
        }

        private static List<Type> ExtractStructTypesFromFile(string assetPath, List<string> wantedStructureTypes)
        {
            List<Type> structureTypes = new List<Type>();
            string[] fileContents = null;
            //open the file and read the contents
            try
            {
                fileContents = File.ReadAllLines(assetPath);
            }
            catch (Exception e)
            {
                Debug.LogError($"Error reading file '{assetPath}': {e.Message}");
                return structureTypes;
            }

            bool getNextLine = false;
            string typeString;
            string[] split;

            //go through each line of the file
            foreach (string line in fileContents)
            {
                if (getNextLine)
                {
                    //split words apart by spaces
                    split = line.Split(' ');

                    //go through each split
                    for (int i = 0; i < split.Length; i++)
                    {
                        //check if our wanted structure type name is contained in the split part
                        if (wantedStructureTypes.Contains(split[i]) && i + 1 < split.Length)
                        {
                            //the next value will be the structure name/type
                            typeString = split[i + 1];
                            structureTypes.Add(StringToType(typeString));
                            break;
                        }
                    }
                    getNextLine = false;
                }
                //check if line contains our [SharedStruct] attribute
                else if (line.Contains($"[{typeof(SharedStruct).Name}]"))
                {
                    //the following line will have the structure name
                    getNextLine = true;
                }
            }
            return structureTypes;
        }

        private static bool ProcessFile(string assetPath)
        {
            //process file into structure types
            List<Type> structureTypes = ExtractStructTypesFromFile(assetPath, new List<string> { "struct", "enum" });
            if (structureTypes.Count == 0)
            {
                return false;
            }

            List<Struct> structs = new List<Struct>();
            List<Struct> enums = new List<Struct>();
            List<Struct> constants = new List<Struct>();
            FieldInfo[] fields;
            Struct currentStruct;

            //iterate through each struct type found in the file
            foreach (Type type in structureTypes)
            {
                if (type == null)
                {
                    continue;
                }

                //create a new struct object for the current type
                currentStruct = new Struct(type.Name, type);
                //retrieve all fields in the struct type
                fields = type.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static);

                //check if the type is an enum or a struct and process accordingly
                if (type.IsEnum && type.GetEnumValues().Length > 0)
                {
                    ProcessEnum(type, ref currentStruct);
                    enums.Add(currentStruct);
                }
                else if (type.IsStruct())
                {
                    //check if the struct is marked as read-only using the IsReadOnlyAttribute attribute
                    if (type.CustomAttributes.Any(attr => attr.AttributeType.FullName == "System.Runtime.CompilerServices.IsReadOnlyAttribute"))
                    {
                        //iterate through each field in the struct type and add it to the struct object if valid
                        foreach (FieldInfo field in fields)
                        {
                            ProcessConstantStructField(field, ref currentStruct);
                        }

                        //only add the current struct if any variables were added
                        if (currentStruct.variables.Count > 0)
                        {
                            constants.Add(currentStruct);
                        }
                    }
                    else
                    {
                        //iterate through each field in the struct type and add it to the struct object if valid
                        foreach (FieldInfo field in fields)
                        {
                            ProcessStructField(field, ref currentStruct);
                        }

                        //only add the current struct if any variables were added
                        if (currentStruct.variables.Count > 0)
                        {
                            structs.Add(currentStruct);
                        }
                    }
                }
            }

            //check if any valid data structures were added
            if (structs.Count > 0)
            {
                //replace any type references with the actual struct pointer within the file, and return a list of external references that need to be imported
                List<string> externalReferences = ReplaceReferences(ref structs);

                //re-order structs to ensure dependencies are met in linear order
                structs = structs.OrderByDependencies(x => x.references, true).ToList();

                //generate output file
                string fileName = Path.GetFileNameWithoutExtension(assetPath);
                WriteOutputFile(fileName, ref structs, ref externalReferences, ref constants, ref enums);
            }

            return true;
        }

        private static void ProcessEnum(Type type, ref Struct currentStruct)
        {
            //add all enum values to the struct object as int variables
            foreach (object obj in type.GetEnumValues())
            {
                string enumName = obj.ToString();
                int enumValue = (int)obj;

                currentStruct.variables.Add(new Variable(enumName, "int", enumValue.ToString()));
            }
        }

        private static void ProcessStructField(FieldInfo field, ref Struct currentStruct)
        {
            string convertedType;

            //check if the field is const or static readonly
            if ((field.IsLiteral && !field.IsInitOnly) || (field.IsInitOnly && field.IsStatic))
            {
                Debug.LogError($"Error at variable '{field.Name}' of type '{field.FieldType.Name}' in struct '{currentStruct.name}'. Constants in standard structs are not supported. Please use a readonly struct to define constants instead.");
                return;
            }

            //check if the field is an array
            if (field.FieldType.IsArray)
            {
                Debug.LogError($"Error at variable '{field.Name}' of type '{field.FieldType.Name}' in struct '{currentStruct.name}'. Arrays without a defined size are not supported (unless marked as const or static readonly). Please set the variable as fixed in an unsafe struct, or use the [MarshalAs()] attribute instead.");
                return;
            }

            //check if the field is a fixed buffer type
            FixedBufferAttribute fixedBufferAttribute = GetFieldAttribute<FixedBufferAttribute>(field);
            if (fixedBufferAttribute != null)
            {
                convertedType = ConvertTypeToHLSL(fixedBufferAttribute.ElementType, field.Name, currentStruct);
                currentStruct.variables.Add(new Variable(field.Name, convertedType, fixedBufferAttribute.Length));
                AddReference(field, ref currentStruct);
                return;
            }

            //check if the field is marshaled as a fixed buffer type with a size constant
            MarshalAsAttribute marshalAsAttribute = GetFieldAttribute<MarshalAsAttribute>(field);
            if (marshalAsAttribute != null)
            {
                convertedType = ConvertTypeToHLSL(field.FieldType, field.Name, currentStruct);
                currentStruct.variables.Add(new Variable(field.Name, convertedType, marshalAsAttribute.SizeConst));
                AddReference(field, ref currentStruct);
                return;
            }

            //add the current variable as it may be valid later once we have all structs added
            convertedType = ConvertTypeToHLSL(field.FieldType, field.Name, currentStruct);
            currentStruct.variables.Add(new Variable(field.Name, convertedType, null));
            AddReference(field, ref currentStruct);
            return;
        }

        private static void ProcessConstantStructField(FieldInfo field, ref Struct currentStruct)
        {
            string convertedType = ConvertTypeToHLSL(field.FieldType, field.Name, currentStruct, true);
            if (convertedType == null)
            {
                return;
            }

            //check if the field is a multidimensional array
            if (field.FieldType.IsArray && field.FieldType.GetArrayRank() > 1)
            {
                Debug.LogError($"Error at variable '{field.Name}' of type '{field.FieldType.Name}' in struct '{currentStruct.name}'. Multi-dimensional arrays are not supported. Please use a one-dimensional array instead");
                return;
            }

            //check if the field is an array
            if (field.FieldType.IsArray)
            {
                Array arrayInstance;
                try
                {
                    //get array instance
                    arrayInstance = (Array)field.GetValue(field.FieldType);

                }
                catch (Exception e)
                {
                    Debug.LogError($"Error at variable '{field.Name}' of type '{field.FieldType.Name}' in struct '{currentStruct.name}'. Error casting field to array: {e.Message}");
                    return;
                }

                List<string> fieldValues = new List<string>();

                //add each element of the array to our value list
                for (int i = 0; i < arrayInstance.Length; i++)
                {
                    fieldValues.Add(arrayInstance.GetValue(i).ToString());
                }

                //add the array to our struct's variables list
                currentStruct.variables.Add(new Variable(field.Name, convertedType, fieldValues, arrayInstance.Length));
                return;
            }

            //add the field to our struct's variables list
            currentStruct.variables.Add(new Variable(field.Name, convertedType, field.GetValue(field.FieldType).ToString()));
        }

        private static void AddReference(FieldInfo field, ref Struct currentDataStructure)
        {
            //only add a reference if the field type isn't a struct
            if (field.FieldType.IsStruct())
            {
                string fileName = null;

                //check if the field type points to another auto-generated struct
                if (field.FieldType.HasAttribute(typeof(SharedStruct)))
                {
                    //find the script file name that defines the struct
                    string[] assetGUIDs = AssetDatabase.FindAssets(field.FieldType.Name + " t:script");

                    if (assetGUIDs.Length > 0)
                    {
                        //get the script file name
                        string scriptFilePath = AssetDatabase.GUIDToAssetPath(assetGUIDs[0]);
                        fileName = Path.GetFileNameWithoutExtension(scriptFilePath);
                    }
                }

                //add temp reference to our current struct
                currentDataStructure.references.Add(new Struct(field.FieldType, fileName));
            }
        }

        private static T GetFieldAttribute<T>(FieldInfo field) where T : Attribute
        {
            Attribute attribute = field.GetCustomAttribute(typeof(T), false);
            if (attribute != null)
            {
                return (T)attribute;
            }
            return null;
        }

        private static List<string> ReplaceReferences(ref List<Struct> structs)
        {
            //replaces any temp struct references with the actual struct within the file, and returns a list of external references that need to be imported
            List<string> externalReferences = new List<string>();
            Struct reference;
            Struct foundStruct;

            foreach (Struct currentStruct in structs)
            {
                for (int i = 0; i < currentStruct.references.Count; i++)
                {
                    reference = currentStruct.references[i];
                    //find existing struct that matches our reference
                    foundStruct = GetStructByType(reference.type, ref structs);

                    //existing struct found, replace the reference with the actual struct
                    if (foundStruct.type != null)
                    {
                        reference = foundStruct;
                    }
                    else
                    {
                        //no reference found, check if it's an external file type reference and add it to the external references list if not already added
                        if (!string.IsNullOrEmpty(reference.fileName) && !externalReferences.Contains(reference.fileName))
                        {
                            externalReferences.Add(reference.fileName);
                        }
                        else
                        {
                            //go through each variable in our struct                            
                            int variableIndex;
                            for (int x = 0; x < currentStruct.variables.Count; x++)
                            {
                                //find if the current variable is using the empty reference, and remove it from the struct if it is
                                variableIndex = currentStruct.variables.FindIndex(x => x.type == reference.type.Name);
                                if (variableIndex != -1)
                                {
                                    Debug.LogError($"Variable '{currentStruct.variables[variableIndex].name}' in struct '{currentStruct.name}' has invalid type '{reference.type.Name}'");
                                    currentStruct.variables.RemoveAt(variableIndex);
                                    x--;
                                }
                            }
                        }

                        //remove reference from struct
                        currentStruct.references.RemoveAt(i);
                        i--;
                    }
                }
            }
            return externalReferences;
        }

        private static Struct GetStructByType(Type type, ref List<Struct> structs)
        {
            foreach (Struct s in structs)
            {
                if (s.type == type)
                {
                    return s;
                }
            }
            return new Struct((Type)null);
        }

        private static Type StringToType(string typeString)
        {
            Type type = Type.GetType(typeString);
            if (type != null)
            {
                return type;
            }
            //if the type is not found in the current domain, search through all assemblies
            foreach (Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                foreach (Type assemblyType in assembly.GetTypes())
                {
                    if (assemblyType.Name == typeString)
                    {
                        type = assemblyType;
                        break;
                    }
                }

                if (type != null)
                {
                    break;
                }
            }
            return type;
        }

        private static string ConvertTypeToHLSL(Type type, string fieldName, Struct currentStruct, bool returnNullIfNotLinked = false)
        {
            string convertedType = type.Name;
            //remove array brackets if present
            convertedType = convertedType.Replace("[", "");
            convertedType = convertedType.Replace("]", "");

            //return null if unsupported
            foreach (Type unsupportedType in unsupportedBuiltInTypes)
            {
                if (unsupportedType.Name == convertedType)
                {
                    Debug.LogError($"Variable '{fieldName}' in struct '{currentStruct.name}' has invalid type '{type.Name}'");
                    return null;
                }
            }
            //return hlsl equivalent for supported types
            foreach (LinkedType linkedType in linkedTypes)
            {
                if (linkedType.cSharpType.Name == convertedType)
                {
                    return linkedType.hlslType;
                }
            }

            if (returnNullIfNotLinked)
            {
                Debug.LogError($"Variable '{fieldName}' in struct '{currentStruct.name}' has invalid type '{type.Name}'");
                return null;
            }

            //return the name of the type if it is not linked to an hlsl type
            return convertedType;
        }

        private static void WriteOutputFile(string fileName, ref List<Struct> structs, ref List<string> externalReferences, ref List<Struct> constants, ref List<Struct> enums)
        {
            //generate .hlsl file header
            StringBuilder fileContents = new StringBuilder();
            fileContents.AppendLine("//");
            fileContents.AppendLine("// AUTO-GENERATED HLSL FILE FOR SHARED STRUCTS, DO NOT MODIFY/ADD CODE AS IT MAY BE OVERWRITTEN");
            fileContents.AppendLine("//");
            fileContents.AppendLine();
            fileContents.AppendLine("#ifndef " + fileName + OUTPUT_FILE_SUFFIX);
            fileContents.AppendLine("#define " + fileName + OUTPUT_FILE_SUFFIX);
            fileContents.AppendLine();

            WriteFileReferences(ref fileContents, ref externalReferences);
            WriteFileEnums(ref fileContents, ref enums);
            WriteFileStructs(ref fileContents, ref structs);
            WriteFileConstants(ref fileContents, ref constants);

            fileContents.AppendLine("#endif");

            string directoryPath = Path.Combine(Application.dataPath, OUTPUT_DIRECTORY);
            string fullPath = Path.Combine(directoryPath, fileName + OUTPUT_FILE_SUFFIX + OUTPUT_FILE_EXTENSION);

            //create directory
            try
            {
                if (!Directory.Exists(directoryPath))
                {
                    Directory.CreateDirectory(directoryPath);
                }
            }
            catch (Exception e)
            {
                Debug.LogError($"Error creating output directory '{directoryPath}': {e.Message}");
                return;
            }

            //create/write file
            try
            {
                File.WriteAllText(fullPath, fileContents.ToString());
            }
            catch (Exception e)
            {
                Debug.LogError($"Error writing to output file '{fullPath}': {e.Message}");
                return;
            }
        }

        private static void WriteFileReferences(ref StringBuilder fileContents, ref List<string> externalReferences)
        {
            foreach (string reference in externalReferences)
            {
                fileContents.AppendLine("#include \"" + reference + OUTPUT_FILE_SUFFIX + OUTPUT_FILE_EXTENSION + "\"");
            }
            fileContents.AppendLine();
        }

        private static void WriteFileStructs(ref StringBuilder fileContents, ref List<Struct> structs)
        {
            foreach (Struct currentStruct in structs)
            {
                fileContents.AppendLine("struct " + currentStruct.type.Name + " {");

                foreach (Variable currentVariable in currentStruct.variables)
                {
                    fileContents.Append("\t" + currentVariable.type + " " + currentVariable.name);

                    if (currentVariable.arrayLength > 0)
                    {
                        fileContents.Append("[" + currentVariable.arrayLength + "]");
                    }

                    fileContents.AppendLine(";");
                }

                fileContents.AppendLine("};");
                fileContents.AppendLine();
            }

            fileContents.AppendLine();
        }

        private static void WriteFileConstants(ref StringBuilder fileContents, ref List<Struct> constants)
        {
            string typeString;
            LinkedType linkedType;
            string values;
            string variableName;

            foreach (Struct currentStruct in constants)
            {
                foreach (Variable variable in currentStruct.variables)
                {
                    typeString = null;
                    linkedType = linkedTypes.FirstOrDefault(x => x.hlslType == variable.type);

                    if (linkedType.displayTypeNameInValueAssignment == true)
                    {
                        typeString = variable.type;
                    }

                    values = "";
                    variableName = variable.name;

                    if (variable.arrayLength > 0)
                    {
                        variableName += "[" + variable.arrayLength + "]";

                        values = "{";
                        foreach (string value in variable.values)
                        {
                            values += typeString + value + ", ";
                        }
                        values = values.TrimEnd(',', ' ') + "}";
                    }
                    else
                    {
                        values = typeString + variable.values[0];
                    }

                    fileContents.AppendLine($"const {variable.type} {variableName} = {values};");
                }
                fileContents.AppendLine();
            }

            fileContents.AppendLine();
        }

        private static void WriteFileEnums(ref StringBuilder fileContents, ref List<Struct> enums)
        {
            foreach (Struct e in enums)
            {
                foreach (Variable variable in e.variables)
                {
                    fileContents.AppendLine($"#define {e.name}_{variable.name} {variable.values[0]}");
                }
                fileContents.AppendLine();
            }

            fileContents.AppendLine();
        }
    }

    /// <summary>
    /// Marks a struct/enum/readonly struct to auto-generate a .hlsl equivalent version of it
    /// </summary>
    [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Enum)]
    public class SharedStruct : Attribute
    {
        public SharedStruct()
        {

        }
    }
}
