using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using Unity.VisualScripting;
using UnityEditor;
using UnityEngine;

namespace UsefulUtilities
{
    /// <summary>
    /// Automatically generates HLSL structs from C# structs marked with the [SharedStruct] attribute
    /// </summary>
    public class SharedStructs : AssetPostprocessor
    {
        private const string OUTPUT_DIRECTORY = "Auto Generated HLSL Structs";
        private const string OUTPUT_FILE_SUFFIX = "_AutoGenerated";
        private const string OUTPUT_FILE_EXTENSION = ".hlsl";
        //hlsl to c# type links
        private static KeyValuePair<string, Type>[] linkedTypes = new KeyValuePair<string, Type>[]
        {
            new KeyValuePair<string, Type>("int", typeof(int)),
            new KeyValuePair<string, Type>("int2", typeof(Vector2Int)),
            new KeyValuePair<string, Type>("int3", typeof(Vector3Int)),
            new KeyValuePair<string, Type>("uint", typeof(uint)),
            new KeyValuePair<string, Type>("float", typeof(float)),
            new KeyValuePair<string, Type>("float2", typeof(Vector2)),
            new KeyValuePair<string, Type>("float3", typeof(Vector3)),
            new KeyValuePair<string, Type>("float4", typeof(Vector4)),
            new KeyValuePair<string, Type>("float4x4", typeof(Matrix4x4))
        };

        private static Type[] unsupportedBuiltInTypes = new Type[]
        {
            typeof(bool),
            typeof(byte),
            typeof(sbyte),
            typeof(char),
            typeof(decimal),
            typeof(double),
            typeof(nint),
            typeof(nuint),
            typeof(long),
            typeof(ulong),
            typeof(short),
            typeof(ushort),
            typeof(object),
            typeof(string),
            typeof(void)
        };

        private struct Struct
        {
            public Type type;
            public List<Variable> variables;
            public List<Struct> references;
            public string fileName;

            public Struct(Type type)
            {
                this.type = type;
                variables = new List<Variable>();
                references = new List<Struct>();
                fileName = null;
            }

            public Struct(Type type, string fileName)
            {
                this.type = type;
                variables = new List<Variable>();
                references = new List<Struct>();
                this.fileName = fileName;
            }
        }

        private struct Variable
        {
            public string name;
            public string typeName;

            public Variable(string name, string typeName)
            {
                this.name = name;
                this.typeName = typeName;
            }
        }

        public static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
        {
            bool fileGenerated = false;

            foreach (string assetPath in importedAssets)
            {
                if (assetPath.EndsWith(".cs") && Path.GetFileNameWithoutExtension(assetPath) != typeof(SharedStructs).Name)
                {
                    fileGenerated = ProcessFile(assetPath);
                }
            }

            if (fileGenerated)
            {
                AssetDatabase.Refresh();
            }
        }

        private static List<Type> ExtractStructsFromFile(string assetPath)
        {
            List<Type> structs = new List<Type>();
            string[] fileContents = null;
            try
            {
                fileContents = File.ReadAllLines(assetPath);
            }
            catch (Exception e)
            {
                Debug.LogError("Error reading file: " + e.Message);
                return structs;
            }

            bool getNextLine = false;
            string typeString;
            string[] split;

            foreach (string line in fileContents)
            {
                if (getNextLine)
                {
                    //check if the line contains the struct keyword and the struct name.
                    split = line.Split(' ');

                    for (int i = 0; i < split.Length; i++)
                    {
                        if (split[i] == "struct" && i + 1 < split.Length)
                        {
                            typeString = split[i + 1];
                            structs.Add(StringToType(typeString));
                            break;
                        }
                    }
                    getNextLine = false;
                }
                else if (line.Contains($"[{typeof(SharedStruct).Name}]"))
                {
                    //the following line will have the struct name
                    getNextLine = true;
                }
            }
            return structs;
        }

        private static bool ProcessFile(string assetPath)
        {
            List<Type> structTypes = ExtractStructsFromFile(assetPath);
            if (structTypes.Count == 0)
            {
                return false;
            }

            List<Struct> structs = new List<Struct>();
            bool addedVariable = false;
            FieldInfo[] fields;
            Struct currentStruct;
            string convertedType;
            Attribute attribute;

            //iterate through each struct type found in the file
            foreach (Type structType in structTypes)
            {
                if (structType == null)
                {
                    continue;
                }

                currentStruct = new Struct(structType);
                fields = structType.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);

                //iterate through each field in the struct type and add it to the struct object if valid
                foreach (FieldInfo field in fields)
                {
                    addedVariable = false;

                    //check if the field is a fixed buffer type
                    attribute = field.GetCustomAttribute(typeof(FixedBufferAttribute), false);
                    if (!addedVariable && attribute != null)
                    {
                        FixedBufferAttribute fixedBufferAttribute = (FixedBufferAttribute)attribute;
                        convertedType = ConvertTypeToHLSL(fixedBufferAttribute.ElementType);
                        if (convertedType == null)
                        {
                            Debug.LogError($"Unsupported variable type '{field.FieldType}' in struct '{structType.Name}'");
                            continue;
                        }
                        currentStruct.variables.Add(new Variable(field.Name + "[" + fixedBufferAttribute.Length + "]", convertedType));
                        addedVariable = true;
                    }

                    //check if the field is marshaled as a fixed buffer type with a size constant
                    attribute = field.GetCustomAttribute(typeof(MarshalAsAttribute), false);
                    if (!addedVariable && attribute != null)
                    {
                        MarshalAsAttribute marshalAsAttribute = (MarshalAsAttribute)attribute;
                        convertedType = ConvertTypeToHLSL(field.FieldType);
                        if (convertedType == null)
                        {
                            Debug.LogError($"Unsupported variable type '{field.FieldType}' in struct '{structType.Name}'");
                            continue;
                        }
                        convertedType = convertedType.Substring(0, convertedType.Length - 2);
                        currentStruct.variables.Add(new Variable(field.Name + "[" + marshalAsAttribute.SizeConst + "]", convertedType));
                        addedVariable = true;
                    }

                    if (!addedVariable)
                    {
                        if (field.FieldType.IsArray)
                        {
                            Debug.LogError("Arrays without a defined size are not supported. Please set the variable as fixed in an unsafe struct, or use the [MarshalAs()] attribute instead.");
                        }
                        else
                        {
                            //add the current variable as it may be valid later once we have all structs added
                            convertedType = ConvertTypeToHLSL(field.FieldType);
                            if (convertedType == null)
                            {
                                Debug.LogError($"Unsupported variable type '{field.FieldType}' in struct '{structType.Name}'");
                                continue;
                            }
                            currentStruct.variables.Add(new Variable(field.Name, convertedType));
                            addedVariable = true;
                        }
                    }

                    //check if the field type points to another auto-generated struct
                    if (addedVariable && field.FieldType.HasAttribute(typeof(SharedStruct)))
                    {
                        //find the script file name that defines the struct and add it as a reference to the current struct
                        string[] assetGUIDs = AssetDatabase.FindAssets(field.FieldType.Name + " t:script");

                        if (assetGUIDs.Length > 0)
                        {
                            string scriptFilePath = AssetDatabase.GUIDToAssetPath(assetGUIDs[0]);
                            //add type and file name reference to the struct
                            currentStruct.references.Add(new Struct(field.FieldType, Path.GetFileNameWithoutExtension(scriptFilePath)));
                        }
                        else
                        {
                            currentStruct.references.Add(new Struct(field.FieldType));
                        }
                    }
                }

                if (currentStruct.variables.Count > 0)
                {
                    structs.Add(currentStruct);
                }
            }

            if (structs.Count > 0)
            {
                //replace any type references with the actual struct pointer within the file, and return a list of external references that need to be imported
                HashSet<string> externalReferences = ReplaceReferences(ref structs);

                //re-order structs to ensure dependencies are met in linear order
                structs = structs.OrderByDependencies(x => x.references, true).ToList();

                //generate output file
                string fileName = Path.GetFileNameWithoutExtension(assetPath);
                WriteOutputFile(fileName, ref structs, ref externalReferences);
            }

            return true;
        }

        private static HashSet<string> ReplaceReferences(ref List<Struct> structs)
        {
            //replace any type references with the actual struct pointer within the file, and return a list of external references that need to be imported
            HashSet<string> externalReferences = new HashSet<string>();
            foreach (Struct s in structs)
            {
                for (int i = 0; i < s.references.Count; i++)
                {
                    Struct foundStruct = GetStructByType(s.references[i].type, ref structs);

                    if (foundStruct.type != null)
                    {
                        s.references[i] = foundStruct;
                    }
                    else
                    {
                        externalReferences.Add(s.references[i].fileName);
                        s.references.RemoveAt(i);
                        i--;
                    }
                }
            }
            return externalReferences;
        }

        private static Struct GetStructByType(Type type, ref List<Struct> structs)
        {
            foreach (Struct s in structs)
            {
                if (s.type == type)
                {
                    return s;
                }
            }
            return new Struct(null);
        }

        private static Type StringToType(string typeString)
        {
            Type type = Type.GetType(typeString);
            if (type != null)
            {
                return type;
            }
            //if the type is not found in the current domain, search through all assemblies
            foreach (Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                foreach (Type assemblyType in assembly.GetTypes())
                {
                    if (assemblyType.Name == typeString)
                    {
                        type = assemblyType;
                        break;
                    }
                }

                if (type != null)
                {
                    break;
                }
            }
            return type;
        }

        private static string ConvertTypeToHLSL(Type type)
        {
            //return null if unsupported
            foreach (Type unsupportedType in unsupportedBuiltInTypes)
            {
                if (unsupportedType == type)
                {
                    return null;
                }
            }
            //return hlsl equivalent for supported types
            foreach (var kvp in linkedTypes)
            {
                if (kvp.Value == type)
                {
                    return kvp.Key;
                }
            }
            //return the name of the type if it is not linked to an hlsl type
            return type.Name;
        }

        private static void WriteOutputFile(string fileName, ref List<Struct> structs, ref HashSet<string> externalReferences)
        {
            //generate .hlsl file
            StringBuilder fileContents = new StringBuilder();
            fileContents.AppendLine("//Auto-generated HLSL file for shared structs, do not modify/add code as it will be overwritten");
            fileContents.AppendLine();
            fileContents.AppendLine("#ifndef " + fileName + OUTPUT_FILE_SUFFIX);
            fileContents.AppendLine("#define " + fileName + OUTPUT_FILE_SUFFIX);
            fileContents.AppendLine();

            foreach (string reference in externalReferences)
            {
                if (reference == null)
                {
                    continue;
                }

                fileContents.AppendLine("#include \"" + reference + OUTPUT_FILE_SUFFIX + OUTPUT_FILE_EXTENSION + "\"");
            }

            fileContents.AppendLine();

            foreach (Struct currentStruct in structs)
            {
                if (currentStruct.type == null)
                {
                    continue;
                }

                fileContents.AppendLine("struct " + currentStruct.type.Name + " {");

                foreach (Variable currentVariable in currentStruct.variables)
                {
                    fileContents.AppendLine("\t" + currentVariable.typeName + " " + currentVariable.name + ";");
                }

                fileContents.AppendLine("};");
                fileContents.AppendLine();
            }

            fileContents.AppendLine();
            fileContents.AppendLine("#endif");

            //create directory & write file
            string directoryPath = Path.Combine(Application.dataPath, OUTPUT_DIRECTORY);

            try
            {
                if (!Directory.Exists(directoryPath))
                {
                    Directory.CreateDirectory(directoryPath);
                }
            }
            catch (Exception e)
            {
                Debug.LogError("Error creating output folder: " + e.Message);
                return;
            }

            string fullPath = Path.Combine(directoryPath, fileName + OUTPUT_FILE_SUFFIX + OUTPUT_FILE_EXTENSION);

            try
            {
                File.WriteAllText(fullPath, fileContents.ToString());
            }
            catch (Exception e)
            {
                Debug.LogError("Error writing file: " + e.Message);
            }
        }
    }

    /// <summary>
    /// Marks a struct to auto-generate a .hlsl equivalent struct
    /// </summary>
    [AttributeUsage(AttributeTargets.Struct)]
    public class SharedStruct : Attribute
    {
        public SharedStruct()
        {

        }
    }
}
